version: '3'
services: 
    nginx:
        image: nginx:1.15.6
        ports:
            - '8000:80'
        depends_on:
            - php
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./laravel:/var/www/html
    php: 
        build: ./docker/php
        volumes:
            - ./laravel:/var/www/html
    mysql:
        image: hypriot/rpi-mysql
        environment:
            MYSQL_DATABASE: omoide
            MYSQL_USER: default
            MYSQL_PASSWORD: default
            MYSQL_ROOT_PASSWORD: default
        ports:
            - '3306:3306'
        volumes:
            - mysql-data:/var/lib/mysql
volumes:
    mysql-data: